
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point r[2] r[2] -type PI PI
add mapped point r[1] r[1] -type PI PI
add mapped point r[0] r[0] -type PI PI
add mapped point row_in[47] row_in[47] -type PI PI
add mapped point row_in[46] row_in[46] -type PI PI
add mapped point row_in[45] row_in[45] -type PI PI
add mapped point row_in[44] row_in[44] -type PI PI
add mapped point row_in[43] row_in[43] -type PI PI
add mapped point row_in[42] row_in[42] -type PI PI
add mapped point row_in[41] row_in[41] -type PI PI
add mapped point row_in[40] row_in[40] -type PI PI
add mapped point row_in[39] row_in[39] -type PI PI
add mapped point row_in[38] row_in[38] -type PI PI
add mapped point row_in[37] row_in[37] -type PI PI
add mapped point row_in[36] row_in[36] -type PI PI
add mapped point row_in[35] row_in[35] -type PI PI
add mapped point row_in[34] row_in[34] -type PI PI
add mapped point row_in[33] row_in[33] -type PI PI
add mapped point row_in[32] row_in[32] -type PI PI
add mapped point row_in[31] row_in[31] -type PI PI
add mapped point row_in[30] row_in[30] -type PI PI
add mapped point row_in[29] row_in[29] -type PI PI
add mapped point row_in[28] row_in[28] -type PI PI
add mapped point row_in[27] row_in[27] -type PI PI
add mapped point row_in[26] row_in[26] -type PI PI
add mapped point row_in[25] row_in[25] -type PI PI
add mapped point row_in[24] row_in[24] -type PI PI
add mapped point row_in[23] row_in[23] -type PI PI
add mapped point row_in[22] row_in[22] -type PI PI
add mapped point row_in[21] row_in[21] -type PI PI
add mapped point row_in[20] row_in[20] -type PI PI
add mapped point row_in[19] row_in[19] -type PI PI
add mapped point row_in[18] row_in[18] -type PI PI
add mapped point row_in[17] row_in[17] -type PI PI
add mapped point row_in[16] row_in[16] -type PI PI
add mapped point row_in[15] row_in[15] -type PI PI
add mapped point row_in[14] row_in[14] -type PI PI
add mapped point row_in[13] row_in[13] -type PI PI
add mapped point row_in[12] row_in[12] -type PI PI
add mapped point row_in[11] row_in[11] -type PI PI
add mapped point row_in[10] row_in[10] -type PI PI
add mapped point row_in[9] row_in[9] -type PI PI
add mapped point row_in[8] row_in[8] -type PI PI
add mapped point row_in[7] row_in[7] -type PI PI
add mapped point row_in[6] row_in[6] -type PI PI
add mapped point row_in[5] row_in[5] -type PI PI
add mapped point row_in[4] row_in[4] -type PI PI
add mapped point row_in[3] row_in[3] -type PI PI
add mapped point row_in[2] row_in[2] -type PI PI
add mapped point row_in[1] row_in[1] -type PI PI
add mapped point row_in[0] row_in[0] -type PI PI
add mapped point sum_val[11] sum_val[11] -type PI PI
add mapped point sum_val[10] sum_val[10] -type PI PI
add mapped point sum_val[9] sum_val[9] -type PI PI
add mapped point sum_val[8] sum_val[8] -type PI PI
add mapped point sum_val[7] sum_val[7] -type PI PI
add mapped point sum_val[6] sum_val[6] -type PI PI
add mapped point sum_val[5] sum_val[5] -type PI PI
add mapped point sum_val[4] sum_val[4] -type PI PI
add mapped point sum_val[3] sum_val[3] -type PI PI
add mapped point sum_val[2] sum_val[2] -type PI PI
add mapped point sum_val[1] sum_val[1] -type PI PI
add mapped point sum_val[0] sum_val[0] -type PI PI

//output ports
add mapped point acc_col1[31] acc_col1[31] -type PO PO
add mapped point acc_col1[30] acc_col1[30] -type PO PO
add mapped point acc_col1[29] acc_col1[29] -type PO PO
add mapped point acc_col1[28] acc_col1[28] -type PO PO
add mapped point acc_col1[27] acc_col1[27] -type PO PO
add mapped point acc_col1[26] acc_col1[26] -type PO PO
add mapped point acc_col1[25] acc_col1[25] -type PO PO
add mapped point acc_col1[24] acc_col1[24] -type PO PO
add mapped point acc_col1[23] acc_col1[23] -type PO PO
add mapped point acc_col1[22] acc_col1[22] -type PO PO
add mapped point acc_col1[21] acc_col1[21] -type PO PO
add mapped point acc_col1[20] acc_col1[20] -type PO PO
add mapped point acc_col1[19] acc_col1[19] -type PO PO
add mapped point acc_col1[18] acc_col1[18] -type PO PO
add mapped point acc_col1[17] acc_col1[17] -type PO PO
add mapped point acc_col1[16] acc_col1[16] -type PO PO
add mapped point acc_col1[15] acc_col1[15] -type PO PO
add mapped point acc_col1[14] acc_col1[14] -type PO PO
add mapped point acc_col1[13] acc_col1[13] -type PO PO
add mapped point acc_col1[12] acc_col1[12] -type PO PO
add mapped point acc_col1[11] acc_col1[11] -type PO PO
add mapped point acc_col1[10] acc_col1[10] -type PO PO
add mapped point acc_col1[9] acc_col1[9] -type PO PO
add mapped point acc_col1[8] acc_col1[8] -type PO PO
add mapped point acc_col1[7] acc_col1[7] -type PO PO
add mapped point acc_col1[6] acc_col1[6] -type PO PO
add mapped point acc_col1[5] acc_col1[5] -type PO PO
add mapped point acc_col1[4] acc_col1[4] -type PO PO
add mapped point acc_col1[3] acc_col1[3] -type PO PO
add mapped point acc_col1[2] acc_col1[2] -type PO PO
add mapped point acc_col1[1] acc_col1[1] -type PO PO
add mapped point acc_col1[0] acc_col1[0] -type PO PO
add mapped point acc_col2[31] acc_col2[31] -type PO PO
add mapped point acc_col2[30] acc_col2[30] -type PO PO
add mapped point acc_col2[29] acc_col2[29] -type PO PO
add mapped point acc_col2[28] acc_col2[28] -type PO PO
add mapped point acc_col2[27] acc_col2[27] -type PO PO
add mapped point acc_col2[26] acc_col2[26] -type PO PO
add mapped point acc_col2[25] acc_col2[25] -type PO PO
add mapped point acc_col2[24] acc_col2[24] -type PO PO
add mapped point acc_col2[23] acc_col2[23] -type PO PO
add mapped point acc_col2[22] acc_col2[22] -type PO PO
add mapped point acc_col2[21] acc_col2[21] -type PO PO
add mapped point acc_col2[20] acc_col2[20] -type PO PO
add mapped point acc_col2[19] acc_col2[19] -type PO PO
add mapped point acc_col2[18] acc_col2[18] -type PO PO
add mapped point acc_col2[17] acc_col2[17] -type PO PO
add mapped point acc_col2[16] acc_col2[16] -type PO PO
add mapped point acc_col2[15] acc_col2[15] -type PO PO
add mapped point acc_col2[14] acc_col2[14] -type PO PO
add mapped point acc_col2[13] acc_col2[13] -type PO PO
add mapped point acc_col2[12] acc_col2[12] -type PO PO
add mapped point acc_col2[11] acc_col2[11] -type PO PO
add mapped point acc_col2[10] acc_col2[10] -type PO PO
add mapped point acc_col2[9] acc_col2[9] -type PO PO
add mapped point acc_col2[8] acc_col2[8] -type PO PO
add mapped point acc_col2[7] acc_col2[7] -type PO PO
add mapped point acc_col2[6] acc_col2[6] -type PO PO
add mapped point acc_col2[5] acc_col2[5] -type PO PO
add mapped point acc_col2[4] acc_col2[4] -type PO PO
add mapped point acc_col2[3] acc_col2[3] -type PO PO
add mapped point acc_col2[2] acc_col2[2] -type PO PO
add mapped point acc_col2[1] acc_col2[1] -type PO PO
add mapped point acc_col2[0] acc_col2[0] -type PO PO
add mapped point acc_col3[31] acc_col3[31] -type PO PO
add mapped point acc_col3[30] acc_col3[30] -type PO PO
add mapped point acc_col3[29] acc_col3[29] -type PO PO
add mapped point acc_col3[28] acc_col3[28] -type PO PO
add mapped point acc_col3[27] acc_col3[27] -type PO PO
add mapped point acc_col3[26] acc_col3[26] -type PO PO
add mapped point acc_col3[25] acc_col3[25] -type PO PO
add mapped point acc_col3[24] acc_col3[24] -type PO PO
add mapped point acc_col3[23] acc_col3[23] -type PO PO
add mapped point acc_col3[22] acc_col3[22] -type PO PO
add mapped point acc_col3[21] acc_col3[21] -type PO PO
add mapped point acc_col3[20] acc_col3[20] -type PO PO
add mapped point acc_col3[19] acc_col3[19] -type PO PO
add mapped point acc_col3[18] acc_col3[18] -type PO PO
add mapped point acc_col3[17] acc_col3[17] -type PO PO
add mapped point acc_col3[16] acc_col3[16] -type PO PO
add mapped point acc_col3[15] acc_col3[15] -type PO PO
add mapped point acc_col3[14] acc_col3[14] -type PO PO
add mapped point acc_col3[13] acc_col3[13] -type PO PO
add mapped point acc_col3[12] acc_col3[12] -type PO PO
add mapped point acc_col3[11] acc_col3[11] -type PO PO
add mapped point acc_col3[10] acc_col3[10] -type PO PO
add mapped point acc_col3[9] acc_col3[9] -type PO PO
add mapped point acc_col3[8] acc_col3[8] -type PO PO
add mapped point acc_col3[7] acc_col3[7] -type PO PO
add mapped point acc_col3[6] acc_col3[6] -type PO PO
add mapped point acc_col3[5] acc_col3[5] -type PO PO
add mapped point acc_col3[4] acc_col3[4] -type PO PO
add mapped point acc_col3[3] acc_col3[3] -type PO PO
add mapped point acc_col3[2] acc_col3[2] -type PO PO
add mapped point acc_col3[1] acc_col3[1] -type PO PO
add mapped point acc_col3[0] acc_col3[0] -type PO PO
add mapped point acc_col4[31] acc_col4[31] -type PO PO
add mapped point acc_col4[30] acc_col4[30] -type PO PO
add mapped point acc_col4[29] acc_col4[29] -type PO PO
add mapped point acc_col4[28] acc_col4[28] -type PO PO
add mapped point acc_col4[27] acc_col4[27] -type PO PO
add mapped point acc_col4[26] acc_col4[26] -type PO PO
add mapped point acc_col4[25] acc_col4[25] -type PO PO
add mapped point acc_col4[24] acc_col4[24] -type PO PO
add mapped point acc_col4[23] acc_col4[23] -type PO PO
add mapped point acc_col4[22] acc_col4[22] -type PO PO
add mapped point acc_col4[21] acc_col4[21] -type PO PO
add mapped point acc_col4[20] acc_col4[20] -type PO PO
add mapped point acc_col4[19] acc_col4[19] -type PO PO
add mapped point acc_col4[18] acc_col4[18] -type PO PO
add mapped point acc_col4[17] acc_col4[17] -type PO PO
add mapped point acc_col4[16] acc_col4[16] -type PO PO
add mapped point acc_col4[15] acc_col4[15] -type PO PO
add mapped point acc_col4[14] acc_col4[14] -type PO PO
add mapped point acc_col4[13] acc_col4[13] -type PO PO
add mapped point acc_col4[12] acc_col4[12] -type PO PO
add mapped point acc_col4[11] acc_col4[11] -type PO PO
add mapped point acc_col4[10] acc_col4[10] -type PO PO
add mapped point acc_col4[9] acc_col4[9] -type PO PO
add mapped point acc_col4[8] acc_col4[8] -type PO PO
add mapped point acc_col4[7] acc_col4[7] -type PO PO
add mapped point acc_col4[6] acc_col4[6] -type PO PO
add mapped point acc_col4[5] acc_col4[5] -type PO PO
add mapped point acc_col4[4] acc_col4[4] -type PO PO
add mapped point acc_col4[3] acc_col4[3] -type PO PO
add mapped point acc_col4[2] acc_col4[2] -type PO PO
add mapped point acc_col4[1] acc_col4[1] -type PO PO
add mapped point acc_col4[0] acc_col4[0] -type PO PO
add mapped point acc_sum[31] acc_sum[31] -type PO PO
add mapped point acc_sum[30] acc_sum[30] -type PO PO
add mapped point acc_sum[29] acc_sum[29] -type PO PO
add mapped point acc_sum[28] acc_sum[28] -type PO PO
add mapped point acc_sum[27] acc_sum[27] -type PO PO
add mapped point acc_sum[26] acc_sum[26] -type PO PO
add mapped point acc_sum[25] acc_sum[25] -type PO PO
add mapped point acc_sum[24] acc_sum[24] -type PO PO
add mapped point acc_sum[23] acc_sum[23] -type PO PO
add mapped point acc_sum[22] acc_sum[22] -type PO PO
add mapped point acc_sum[21] acc_sum[21] -type PO PO
add mapped point acc_sum[20] acc_sum[20] -type PO PO
add mapped point acc_sum[19] acc_sum[19] -type PO PO
add mapped point acc_sum[18] acc_sum[18] -type PO PO
add mapped point acc_sum[17] acc_sum[17] -type PO PO
add mapped point acc_sum[16] acc_sum[16] -type PO PO
add mapped point acc_sum[15] acc_sum[15] -type PO PO
add mapped point acc_sum[14] acc_sum[14] -type PO PO
add mapped point acc_sum[13] acc_sum[13] -type PO PO
add mapped point acc_sum[12] acc_sum[12] -type PO PO
add mapped point acc_sum[11] acc_sum[11] -type PO PO
add mapped point acc_sum[10] acc_sum[10] -type PO PO
add mapped point acc_sum[9] acc_sum[9] -type PO PO
add mapped point acc_sum[8] acc_sum[8] -type PO PO
add mapped point acc_sum[7] acc_sum[7] -type PO PO
add mapped point acc_sum[6] acc_sum[6] -type PO PO
add mapped point acc_sum[5] acc_sum[5] -type PO PO
add mapped point acc_sum[4] acc_sum[4] -type PO PO
add mapped point acc_sum[3] acc_sum[3] -type PO PO
add mapped point acc_sum[2] acc_sum[2] -type PO PO
add mapped point acc_sum[1] acc_sum[1] -type PO PO
add mapped point acc_sum[0] acc_sum[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point acc_col1[0]/q acc_col1_reg[0]/Q -type DFF DFF
add mapped point acc_col1[1]/q acc_col1_reg[1]/Q -type DFF DFF
add mapped point acc_col1[2]/q acc_col1_reg[2]/Q -type DFF DFF
add mapped point acc_col1[3]/q acc_col1_reg[3]/Q -type DFF DFF
add mapped point acc_col1[4]/q acc_col1_reg[4]/Q -type DFF DFF
add mapped point acc_col1[5]/q acc_col1_reg[5]/Q -type DFF DFF
add mapped point acc_col1[6]/q acc_col1_reg[6]/Q -type DFF DFF
add mapped point acc_col1[7]/q acc_col1_reg[7]/Q -type DFF DFF
add mapped point acc_col1[8]/q acc_col1_reg[8]/Q -type DFF DFF
add mapped point acc_col1[9]/q acc_col1_reg[9]/Q -type DFF DFF
add mapped point acc_col1[10]/q acc_col1_reg[10]/Q -type DFF DFF
add mapped point acc_col1[11]/q acc_col1_reg[11]/Q -type DFF DFF
add mapped point acc_col1[12]/q acc_col1_reg[12]/Q -type DFF DFF
add mapped point acc_col1[13]/q acc_col1_reg[13]/Q -type DFF DFF
add mapped point acc_col1[14]/q acc_col1_reg[14]/Q -type DFF DFF
add mapped point acc_col1[15]/q acc_col1_reg[15]/Q -type DFF DFF
add mapped point acc_col1[16]/q acc_col1_reg[16]/Q -type DFF DFF
add mapped point acc_col1[17]/q acc_col1_reg[17]/Q -type DFF DFF
add mapped point acc_col1[18]/q acc_col1_reg[18]/Q -type DFF DFF
add mapped point acc_col1[19]/q acc_col1_reg[19]/Q -type DFF DFF
add mapped point acc_col1[20]/q acc_col1_reg[20]/Q -type DFF DFF
add mapped point acc_col1[21]/q acc_col1_reg[21]/Q -type DFF DFF
add mapped point acc_col1[22]/q acc_col1_reg[22]/Q -type DFF DFF
add mapped point acc_col1[23]/q acc_col1_reg[23]/Q -type DFF DFF
add mapped point acc_col1[24]/q acc_col1_reg[24]/Q -type DFF DFF
add mapped point acc_col1[25]/q acc_col1_reg[25]/Q -type DFF DFF
add mapped point acc_col1[26]/q acc_col1_reg[26]/Q -type DFF DFF
add mapped point acc_col1[27]/q acc_col1_reg[27]/Q -type DFF DFF
add mapped point acc_col1[28]/q acc_col1_reg[28]/Q -type DFF DFF
add mapped point acc_col1[29]/q acc_col1_reg[29]/Q -type DFF DFF
add mapped point acc_col1[30]/q acc_col1_reg[30]/Q -type DFF DFF
add mapped point acc_col1[31]/q acc_col1_reg[31]/Q -type DFF DFF
add mapped point acc_col2[0]/q acc_col2_reg[0]/Q -type DFF DFF
add mapped point acc_col2[1]/q acc_col2_reg[1]/Q -type DFF DFF
add mapped point acc_col2[2]/q acc_col2_reg[2]/Q -type DFF DFF
add mapped point acc_col2[3]/q acc_col2_reg[3]/Q -type DFF DFF
add mapped point acc_col2[4]/q acc_col2_reg[4]/Q -type DFF DFF
add mapped point acc_col2[5]/q acc_col2_reg[5]/Q -type DFF DFF
add mapped point acc_col2[6]/q acc_col2_reg[6]/Q -type DFF DFF
add mapped point acc_col2[7]/q acc_col2_reg[7]/Q -type DFF DFF
add mapped point acc_col2[8]/q acc_col2_reg[8]/Q -type DFF DFF
add mapped point acc_col2[9]/q acc_col2_reg[9]/Q -type DFF DFF
add mapped point acc_col2[10]/q acc_col2_reg[10]/Q -type DFF DFF
add mapped point acc_col2[11]/q acc_col2_reg[11]/Q -type DFF DFF
add mapped point acc_col2[12]/q acc_col2_reg[12]/Q -type DFF DFF
add mapped point acc_col2[13]/q acc_col2_reg[13]/Q -type DFF DFF
add mapped point acc_col2[14]/q acc_col2_reg[14]/Q -type DFF DFF
add mapped point acc_col2[15]/q acc_col2_reg[15]/Q -type DFF DFF
add mapped point acc_col2[16]/q acc_col2_reg[16]/Q -type DFF DFF
add mapped point acc_col2[17]/q acc_col2_reg[17]/Q -type DFF DFF
add mapped point acc_col2[18]/q acc_col2_reg[18]/Q -type DFF DFF
add mapped point acc_col2[19]/q acc_col2_reg[19]/Q -type DFF DFF
add mapped point acc_col2[20]/q acc_col2_reg[20]/Q -type DFF DFF
add mapped point acc_col2[21]/q acc_col2_reg[21]/Q -type DFF DFF
add mapped point acc_col2[22]/q acc_col2_reg[22]/Q -type DFF DFF
add mapped point acc_col2[23]/q acc_col2_reg[23]/Q -type DFF DFF
add mapped point acc_col2[24]/q acc_col2_reg[24]/Q -type DFF DFF
add mapped point acc_col2[25]/q acc_col2_reg[25]/Q -type DFF DFF
add mapped point acc_col2[26]/q acc_col2_reg[26]/Q -type DFF DFF
add mapped point acc_col2[27]/q acc_col2_reg[27]/Q -type DFF DFF
add mapped point acc_col2[28]/q acc_col2_reg[28]/Q -type DFF DFF
add mapped point acc_col2[29]/q acc_col2_reg[29]/Q -type DFF DFF
add mapped point acc_col2[30]/q acc_col2_reg[30]/Q -type DFF DFF
add mapped point acc_col2[31]/q acc_col2_reg[31]/Q -type DFF DFF
add mapped point acc_col3[0]/q acc_col3_reg[0]/Q -type DFF DFF
add mapped point acc_col3[1]/q acc_col3_reg[1]/Q -type DFF DFF
add mapped point acc_col3[2]/q acc_col3_reg[2]/Q -type DFF DFF
add mapped point acc_col3[3]/q acc_col3_reg[3]/Q -type DFF DFF
add mapped point acc_col3[4]/q acc_col3_reg[4]/Q -type DFF DFF
add mapped point acc_col3[5]/q acc_col3_reg[5]/Q -type DFF DFF
add mapped point acc_col3[6]/q acc_col3_reg[6]/Q -type DFF DFF
add mapped point acc_col3[7]/q acc_col3_reg[7]/Q -type DFF DFF
add mapped point acc_col3[8]/q acc_col3_reg[8]/Q -type DFF DFF
add mapped point acc_col3[9]/q acc_col3_reg[9]/Q -type DFF DFF
add mapped point acc_col3[10]/q acc_col3_reg[10]/Q -type DFF DFF
add mapped point acc_col3[11]/q acc_col3_reg[11]/Q -type DFF DFF
add mapped point acc_col3[12]/q acc_col3_reg[12]/Q -type DFF DFF
add mapped point acc_col3[13]/q acc_col3_reg[13]/Q -type DFF DFF
add mapped point acc_col3[14]/q acc_col3_reg[14]/Q -type DFF DFF
add mapped point acc_col3[15]/q acc_col3_reg[15]/Q -type DFF DFF
add mapped point acc_col3[16]/q acc_col3_reg[16]/Q -type DFF DFF
add mapped point acc_col3[17]/q acc_col3_reg[17]/Q -type DFF DFF
add mapped point acc_col3[18]/q acc_col3_reg[18]/Q -type DFF DFF
add mapped point acc_col3[19]/q acc_col3_reg[19]/Q -type DFF DFF
add mapped point acc_col3[20]/q acc_col3_reg[20]/Q -type DFF DFF
add mapped point acc_col3[21]/q acc_col3_reg[21]/Q -type DFF DFF
add mapped point acc_col3[22]/q acc_col3_reg[22]/Q -type DFF DFF
add mapped point acc_col3[23]/q acc_col3_reg[23]/Q -type DFF DFF
add mapped point acc_col3[24]/q acc_col3_reg[24]/Q -type DFF DFF
add mapped point acc_col3[25]/q acc_col3_reg[25]/Q -type DFF DFF
add mapped point acc_col3[26]/q acc_col3_reg[26]/Q -type DFF DFF
add mapped point acc_col3[27]/q acc_col3_reg[27]/Q -type DFF DFF
add mapped point acc_col3[28]/q acc_col3_reg[28]/Q -type DFF DFF
add mapped point acc_col3[29]/q acc_col3_reg[29]/Q -type DFF DFF
add mapped point acc_col3[30]/q acc_col3_reg[30]/Q -type DFF DFF
add mapped point acc_col3[31]/q acc_col3_reg[31]/Q -type DFF DFF
add mapped point acc_col4[0]/q acc_col4_reg[0]/Q -type DFF DFF
add mapped point acc_col4[1]/q acc_col4_reg[1]/Q -type DFF DFF
add mapped point acc_col4[2]/q acc_col4_reg[2]/Q -type DFF DFF
add mapped point acc_col4[3]/q acc_col4_reg[3]/Q -type DFF DFF
add mapped point acc_col4[4]/q acc_col4_reg[4]/Q -type DFF DFF
add mapped point acc_col4[5]/q acc_col4_reg[5]/Q -type DFF DFF
add mapped point acc_col4[6]/q acc_col4_reg[6]/Q -type DFF DFF
add mapped point acc_col4[7]/q acc_col4_reg[7]/Q -type DFF DFF
add mapped point acc_col4[8]/q acc_col4_reg[8]/Q -type DFF DFF
add mapped point acc_col4[9]/q acc_col4_reg[9]/Q -type DFF DFF
add mapped point acc_col4[10]/q acc_col4_reg[10]/Q -type DFF DFF
add mapped point acc_col4[11]/q acc_col4_reg[11]/Q -type DFF DFF
add mapped point acc_col4[12]/q acc_col4_reg[12]/Q -type DFF DFF
add mapped point acc_col4[13]/q acc_col4_reg[13]/Q -type DFF DFF
add mapped point acc_col4[14]/q acc_col4_reg[14]/Q -type DFF DFF
add mapped point acc_col4[15]/q acc_col4_reg[15]/Q -type DFF DFF
add mapped point acc_col4[16]/q acc_col4_reg[16]/Q -type DFF DFF
add mapped point acc_col4[17]/q acc_col4_reg[17]/Q -type DFF DFF
add mapped point acc_col4[18]/q acc_col4_reg[18]/Q -type DFF DFF
add mapped point acc_col4[19]/q acc_col4_reg[19]/Q -type DFF DFF
add mapped point acc_col4[20]/q acc_col4_reg[20]/Q -type DFF DFF
add mapped point acc_col4[21]/q acc_col4_reg[21]/Q -type DFF DFF
add mapped point acc_col4[22]/q acc_col4_reg[22]/Q -type DFF DFF
add mapped point acc_col4[23]/q acc_col4_reg[23]/Q -type DFF DFF
add mapped point acc_col4[24]/q acc_col4_reg[24]/Q -type DFF DFF
add mapped point acc_col4[25]/q acc_col4_reg[25]/Q -type DFF DFF
add mapped point acc_col4[26]/q acc_col4_reg[26]/Q -type DFF DFF
add mapped point acc_col4[27]/q acc_col4_reg[27]/Q -type DFF DFF
add mapped point acc_col4[28]/q acc_col4_reg[28]/Q -type DFF DFF
add mapped point acc_col4[29]/q acc_col4_reg[29]/Q -type DFF DFF
add mapped point acc_col4[30]/q acc_col4_reg[30]/Q -type DFF DFF
add mapped point acc_col4[31]/q acc_col4_reg[31]/Q -type DFF DFF
add mapped point acc_sum[0]/q acc_sum_reg[0]/Q -type DFF DFF
add mapped point acc_sum[1]/q acc_sum_reg[1]/Q -type DFF DFF
add mapped point acc_sum[2]/q acc_sum_reg[2]/Q -type DFF DFF
add mapped point acc_sum[3]/q acc_sum_reg[3]/Q -type DFF DFF
add mapped point acc_sum[4]/q acc_sum_reg[4]/Q -type DFF DFF
add mapped point acc_sum[5]/q acc_sum_reg[5]/Q -type DFF DFF
add mapped point acc_sum[6]/q acc_sum_reg[6]/Q -type DFF DFF
add mapped point acc_sum[7]/q acc_sum_reg[7]/Q -type DFF DFF
add mapped point acc_sum[8]/q acc_sum_reg[8]/Q -type DFF DFF
add mapped point acc_sum[9]/q acc_sum_reg[9]/Q -type DFF DFF
add mapped point acc_sum[10]/q acc_sum_reg[10]/Q -type DFF DFF
add mapped point acc_sum[11]/q acc_sum_reg[11]/Q -type DFF DFF
add mapped point acc_sum[12]/q acc_sum_reg[12]/Q -type DFF DFF
add mapped point acc_sum[13]/q acc_sum_reg[13]/Q -type DFF DFF
add mapped point acc_sum[14]/q acc_sum_reg[14]/Q -type DFF DFF
add mapped point acc_sum[15]/q acc_sum_reg[15]/Q -type DFF DFF
add mapped point acc_sum[16]/q acc_sum_reg[16]/Q -type DFF DFF
add mapped point acc_sum[17]/q acc_sum_reg[17]/Q -type DFF DFF
add mapped point acc_sum[18]/q acc_sum_reg[18]/Q -type DFF DFF
add mapped point acc_sum[19]/q acc_sum_reg[19]/Q -type DFF DFF
add mapped point acc_sum[20]/q acc_sum_reg[20]/Q -type DFF DFF
add mapped point acc_sum[21]/q acc_sum_reg[21]/Q -type DFF DFF
add mapped point acc_sum[22]/q acc_sum_reg[22]/Q -type DFF DFF
add mapped point acc_sum[23]/q acc_sum_reg[23]/Q -type DFF DFF
add mapped point acc_sum[24]/q acc_sum_reg[24]/Q -type DFF DFF
add mapped point acc_sum[25]/q acc_sum_reg[25]/Q -type DFF DFF
add mapped point acc_sum[26]/q acc_sum_reg[26]/Q -type DFF DFF
add mapped point acc_sum[27]/q acc_sum_reg[27]/Q -type DFF DFF
add mapped point acc_sum[28]/q acc_sum_reg[28]/Q -type DFF DFF
add mapped point acc_sum[29]/q acc_sum_reg[29]/Q -type DFF DFF
add mapped point acc_sum[30]/q acc_sum_reg[30]/Q -type DFF DFF
add mapped point acc_sum[31]/q acc_sum_reg[31]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
