
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point start start -type PI PI
add mapped point A[31] A[31] -type PI PI
add mapped point A[30] A[30] -type PI PI
add mapped point A[29] A[29] -type PI PI
add mapped point A[28] A[28] -type PI PI
add mapped point A[27] A[27] -type PI PI
add mapped point A[26] A[26] -type PI PI
add mapped point A[25] A[25] -type PI PI
add mapped point A[24] A[24] -type PI PI
add mapped point A[23] A[23] -type PI PI
add mapped point A[22] A[22] -type PI PI
add mapped point A[21] A[21] -type PI PI
add mapped point A[20] A[20] -type PI PI
add mapped point A[19] A[19] -type PI PI
add mapped point A[18] A[18] -type PI PI
add mapped point A[17] A[17] -type PI PI
add mapped point A[16] A[16] -type PI PI
add mapped point A[15] A[15] -type PI PI
add mapped point A[14] A[14] -type PI PI
add mapped point A[13] A[13] -type PI PI
add mapped point A[12] A[12] -type PI PI
add mapped point A[11] A[11] -type PI PI
add mapped point A[10] A[10] -type PI PI
add mapped point A[9] A[9] -type PI PI
add mapped point A[8] A[8] -type PI PI
add mapped point A[7] A[7] -type PI PI
add mapped point A[6] A[6] -type PI PI
add mapped point A[5] A[5] -type PI PI
add mapped point A[4] A[4] -type PI PI
add mapped point A[3] A[3] -type PI PI
add mapped point A[2] A[2] -type PI PI
add mapped point A[1] A[1] -type PI PI
add mapped point A[0] A[0] -type PI PI
add mapped point B[31] B[31] -type PI PI
add mapped point B[30] B[30] -type PI PI
add mapped point B[29] B[29] -type PI PI
add mapped point B[28] B[28] -type PI PI
add mapped point B[27] B[27] -type PI PI
add mapped point B[26] B[26] -type PI PI
add mapped point B[25] B[25] -type PI PI
add mapped point B[24] B[24] -type PI PI
add mapped point B[23] B[23] -type PI PI
add mapped point B[22] B[22] -type PI PI
add mapped point B[21] B[21] -type PI PI
add mapped point B[20] B[20] -type PI PI
add mapped point B[19] B[19] -type PI PI
add mapped point B[18] B[18] -type PI PI
add mapped point B[17] B[17] -type PI PI
add mapped point B[16] B[16] -type PI PI
add mapped point B[15] B[15] -type PI PI
add mapped point B[14] B[14] -type PI PI
add mapped point B[13] B[13] -type PI PI
add mapped point B[12] B[12] -type PI PI
add mapped point B[11] B[11] -type PI PI
add mapped point B[10] B[10] -type PI PI
add mapped point B[9] B[9] -type PI PI
add mapped point B[8] B[8] -type PI PI
add mapped point B[7] B[7] -type PI PI
add mapped point B[6] B[6] -type PI PI
add mapped point B[5] B[5] -type PI PI
add mapped point B[4] B[4] -type PI PI
add mapped point B[3] B[3] -type PI PI
add mapped point B[2] B[2] -type PI PI
add mapped point B[1] B[1] -type PI PI
add mapped point B[0] B[0] -type PI PI

//output ports
add mapped point result[31] result[31] -type PO PO
add mapped point result[30] result[30] -type PO PO
add mapped point result[29] result[29] -type PO PO
add mapped point result[28] result[28] -type PO PO
add mapped point result[27] result[27] -type PO PO
add mapped point result[26] result[26] -type PO PO
add mapped point result[25] result[25] -type PO PO
add mapped point result[24] result[24] -type PO PO
add mapped point result[23] result[23] -type PO PO
add mapped point result[22] result[22] -type PO PO
add mapped point result[21] result[21] -type PO PO
add mapped point result[20] result[20] -type PO PO
add mapped point result[19] result[19] -type PO PO
add mapped point result[18] result[18] -type PO PO
add mapped point result[17] result[17] -type PO PO
add mapped point result[16] result[16] -type PO PO
add mapped point result[15] result[15] -type PO PO
add mapped point result[14] result[14] -type PO PO
add mapped point result[13] result[13] -type PO PO
add mapped point result[12] result[12] -type PO PO
add mapped point result[11] result[11] -type PO PO
add mapped point result[10] result[10] -type PO PO
add mapped point result[9] result[9] -type PO PO
add mapped point result[8] result[8] -type PO PO
add mapped point result[7] result[7] -type PO PO
add mapped point result[6] result[6] -type PO PO
add mapped point result[5] result[5] -type PO PO
add mapped point result[4] result[4] -type PO PO
add mapped point result[3] result[3] -type PO PO
add mapped point result[2] result[2] -type PO PO
add mapped point result[1] result[1] -type PO PO
add mapped point result[0] result[0] -type PO PO
add mapped point done done -type PO PO

//inout ports




//Sequential Pins
add mapped point dividend[28]/q dividend_reg[28]/Q -type DFF DFF
add mapped point dividend[31]/q dividend_reg[31]/Q -type DFF DFF
add mapped point dividend[19]/q dividend_reg[19]/Q -type DFF DFF
add mapped point dividend[25]/q dividend_reg[25]/Q -type DFF DFF
add mapped point dividend[26]/q dividend_reg[26]/Q -type DFF DFF
add mapped point dividend[27]/q dividend_reg[27]/Q -type DFF DFF
add mapped point dividend[29]/q dividend_reg[29]/Q -type DFF DFF
add mapped point dividend[24]/q dividend_reg[24]/Q -type DFF DFF
add mapped point dividend[17]/q dividend_reg[17]/Q -type DFF DFF
add mapped point dividend[22]/q dividend_reg[22]/Q -type DFF DFF
add mapped point dividend[20]/q dividend_reg[20]/Q -type DFF DFF
add mapped point dividend[18]/q dividend_reg[18]/Q -type DFF DFF
add mapped point dividend[21]/q dividend_reg[21]/Q -type DFF DFF
add mapped point dividend[30]/q dividend_reg[30]/Q -type DFF DFF
add mapped point dividend[23]/q dividend_reg[23]/Q -type DFF DFF
add mapped point dividend[11]/q dividend_reg[11]/Q -type DFF DFF
add mapped point shift[5]/q shift_reg[5]/Q -type DFF DFF
add mapped point dividend[14]/q dividend_reg[14]/Q -type DFF DFF
add mapped point dividend[6]/q dividend_reg[6]/Q -type DFF DFF
add mapped point dividend[16]/q dividend_reg[16]/Q -type DFF DFF
add mapped point dividend[1]/q dividend_reg[1]/Q -type DFF DFF
add mapped point dividend[13]/q dividend_reg[13]/Q -type DFF DFF
add mapped point dividend[0]/q dividend_reg[0]/Q -type DFF DFF
add mapped point dividend[3]/q dividend_reg[3]/Q -type DFF DFF
add mapped point dividend[8]/q dividend_reg[8]/Q -type DFF DFF
add mapped point dividend[10]/q dividend_reg[10]/Q -type DFF DFF
add mapped point dividend[5]/q dividend_reg[5]/Q -type DFF DFF
add mapped point dividend[9]/q dividend_reg[9]/Q -type DFF DFF
add mapped point dividend[12]/q dividend_reg[12]/Q -type DFF DFF
add mapped point dividend[2]/q dividend_reg[2]/Q -type DFF DFF
add mapped point dividend[15]/q dividend_reg[15]/Q -type DFF DFF
add mapped point dividend[4]/q dividend_reg[4]/Q -type DFF DFF
add mapped point dividend[7]/q dividend_reg[7]/Q -type DFF DFF
add mapped point shift[4]/q shift_reg[4]/Q -type DFF DFF
add mapped point shift[2]/q shift_reg[2]/Q -type DFF DFF
add mapped point divisor[31]/q divisor_reg[31]/Q -type DFF DFF
add mapped point divisor[22]/q divisor_reg[22]/Q -type DFF DFF
add mapped point divisor[18]/q divisor_reg[18]/Q -type DFF DFF
add mapped point divisor[16]/q divisor_reg[16]/Q -type DFF DFF
add mapped point divisor[20]/q divisor_reg[20]/Q -type DFF DFF
add mapped point divisor[1]/q divisor_reg[1]/Q -type DFF DFF
add mapped point divisor[23]/q divisor_reg[23]/Q -type DFF DFF
add mapped point divisor[21]/q divisor_reg[21]/Q -type DFF DFF
add mapped point divisor[24]/q divisor_reg[24]/Q -type DFF DFF
add mapped point divisor[11]/q divisor_reg[11]/Q -type DFF DFF
add mapped point shift[3]/q shift_reg[3]/Q -type DFF DFF
add mapped point divisor[6]/q divisor_reg[6]/Q -type DFF DFF
add mapped point divisor[15]/q divisor_reg[15]/Q -type DFF DFF
add mapped point divisor[26]/q divisor_reg[26]/Q -type DFF DFF
add mapped point divisor[5]/q divisor_reg[5]/Q -type DFF DFF
add mapped point divisor[3]/q divisor_reg[3]/Q -type DFF DFF
add mapped point divisor[28]/q divisor_reg[28]/Q -type DFF DFF
add mapped point shift[1]/q shift_reg[1]/Q -type DFF DFF
add mapped point divisor[7]/q divisor_reg[7]/Q -type DFF DFF
add mapped point divisor[2]/q divisor_reg[2]/Q -type DFF DFF
add mapped point divisor[4]/q divisor_reg[4]/Q -type DFF DFF
add mapped point divisor[29]/q divisor_reg[29]/Q -type DFF DFF
add mapped point divisor[19]/q divisor_reg[19]/Q -type DFF DFF
add mapped point divisor[30]/q divisor_reg[30]/Q -type DFF DFF
add mapped point divisor[13]/q divisor_reg[13]/Q -type DFF DFF
add mapped point divisor[25]/q divisor_reg[25]/Q -type DFF DFF
add mapped point divisor[14]/q divisor_reg[14]/Q -type DFF DFF
add mapped point divisor[12]/q divisor_reg[12]/Q -type DFF DFF
add mapped point divisor[27]/q divisor_reg[27]/Q -type DFF DFF
add mapped point divisor[8]/q divisor_reg[8]/Q -type DFF DFF
add mapped point divisor[10]/q divisor_reg[10]/Q -type DFF DFF
add mapped point divisor[9]/q divisor_reg[9]/Q -type DFF DFF
add mapped point divisor[17]/q divisor_reg[17]/Q -type DFF DFF
add mapped point shift[0]/q shift_reg[0]/Q -type DFF DFF
add mapped point divisor[0]/q divisor_reg[0]/Q -type DFF DFF
add mapped point state[0]/q state_reg[0]/Q -type DFF DFF
add mapped point state[1]/q state_reg[1]/Q -type DFF DFF
add mapped point result[24]/q result_reg[24]/Q -type DFF DFF
add mapped point result[31]/q result_reg[31]/Q -type DFF DFF
add mapped point result[30]/q result_reg[30]/Q -type DFF DFF
add mapped point result[15]/q result_reg[15]/Q -type DFF DFF
add mapped point result[4]/q result_reg[4]/Q -type DFF DFF
add mapped point result[17]/q result_reg[17]/Q -type DFF DFF
add mapped point result[23]/q result_reg[23]/Q -type DFF DFF
add mapped point result[14]/q result_reg[14]/Q -type DFF DFF
add mapped point result[25]/q result_reg[25]/Q -type DFF DFF
add mapped point result[21]/q result_reg[21]/Q -type DFF DFF
add mapped point result[20]/q result_reg[20]/Q -type DFF DFF
add mapped point result[16]/q result_reg[16]/Q -type DFF DFF
add mapped point result[22]/q result_reg[22]/Q -type DFF DFF
add mapped point result[1]/q result_reg[1]/Q -type DFF DFF
add mapped point result[7]/q result_reg[7]/Q -type DFF DFF
add mapped point result[8]/q result_reg[8]/Q -type DFF DFF
add mapped point result[27]/q result_reg[27]/Q -type DFF DFF
add mapped point result[26]/q result_reg[26]/Q -type DFF DFF
add mapped point result[9]/q result_reg[9]/Q -type DFF DFF
add mapped point result[12]/q result_reg[12]/Q -type DFF DFF
add mapped point result[0]/q result_reg[0]/Q -type DFF DFF
add mapped point result[3]/q result_reg[3]/Q -type DFF DFF
add mapped point result[5]/q result_reg[5]/Q -type DFF DFF
add mapped point result[13]/q result_reg[13]/Q -type DFF DFF
add mapped point result[18]/q result_reg[18]/Q -type DFF DFF
add mapped point result[29]/q result_reg[29]/Q -type DFF DFF
add mapped point result[28]/q result_reg[28]/Q -type DFF DFF
add mapped point result[6]/q result_reg[6]/Q -type DFF DFF
add mapped point result[19]/q result_reg[19]/Q -type DFF DFF
add mapped point result[2]/q result_reg[2]/Q -type DFF DFF
add mapped point result[10]/q result_reg[10]/Q -type DFF DFF
add mapped point result[11]/q result_reg[11]/Q -type DFF DFF
add mapped point done/q done_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
